### PR TITLE
Replace getting options for validation rules with getters

### PR DESCRIPTION
**Pull request by arogachev**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/validator/issues/225#issuecomment-1205595119

### CODE REVIEW

**Review by rustamwin — COMMENTED** [review]
Need to remove psalm suppress.

**Comment by arogachev** [comment]
@rustamwin OK. Done.

**Comment by arogachev** [comment]
I reverted the changes with Psalm because this was not the case. https://github.com/yiisoft/form/runs/7702716871?check_suite_focus=true

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
