### PR TITLE
Sync with validator and html

### PR DESCRIPTION
**Pull request by arogachev**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/validator/pull/274

### CODE REVIEW

**Comment by samdark** [comment]
@arogachev would you please resolve conflicts?

**Comment by arogachev** [comment]
@samdark Sure. Done. Forgot to pull changes from "master" branch, sorry.

**Comment by arogachev** [comment]
Tests are failing now. `admin@.com` is a vaild email address now somehow. :thinking: Probably regression caused by the latest validator changes. I will check.

**Comment by arogachev** [comment]
Fixed other problems as well.

**Comment by samdark** [comment]
👍

**Pull request merged**
